import pygame as pg

PRIMARIES = [
    "Liberator", 
    "Liberator Penatrator", 
    "Liberator Concussive", 
    "Liberator Carbine",
    "Tenderizer",
    "Adjudicator",
    "Cookout",
    "Purifier",
    "Torcher",
    "Knight", 
    "Defender", 
    "Pummeler", 
    "Punisher", 
    "Slugger", 
    "Breaker", 
    "Breaker Incendiary", 
    "Breaker Spray & Pray", 
    "Diligence", 
    "Diligence Counter Sniper", 
    "Scythe", 
    "Sickle", 
    "Scorcher", 
    "Punisher Plasma", 
    "Blitzer", 
    "Dominator", 
    "Erupter",
    "Exploding Crossbow",
    "Reprimand",
    "Constitution",
    "Halt",
    ]

SECONDARIES = [
    "Crisper",
    "Dagger",
    "Peacemaker",
    "Redeemer", 
    "Grenade Pistol", 
    "Verdict",
    "Senator", 
    "Stim Pistol", 
    "Bushwhacker",
    "Loyalist",
    ]

GRENADES = [
    "Gas Grenade",
    "Throwing Knife",
    "High Explosive Grenade", 
    "Frag Grenade", 
    "Impact Grenade", 
    "Smoke Grenade", 
    "Incendiary Grenade", 
    "Stun Grenade", 
    "Thermite Grenade", 
    "Incendiary Impact"
    ]

STRATEGEMS = {
    "Eagle Strafing Run":           ["Eagle"],
    "Eagle Airstrike":              ["Eagle"],
    "Eagle Cluster Bomb":           ["Eagle"],
    "Eagle Napalm Strike":          ["Eagle"],
    "Eagle Smoke Strike":           ["Eagle"],
    "Eagle 110MM Rocket Pods":      ["Eagle"],
    "Eagle 500kg Bomb":             ["Eagle"],
    "Orbital Precision Strike":     ["Orbital"],
    "Orbital Airburst Strike":      ["Orbital"],
    "Orbital 120MM HE Barrage":     ["Orbital"],
    "Orbital 380MM HE Barrage":     ["Orbital"],
    "Orbital Walking Barrage":      ["Orbital"],
    "Orbital Laser":                ["Orbital"],
    "Orbital Railcannon Strike":    ["Orbital"],
    "Orbital Gatling Barrage":      ["Orbital"],
    "Orbital Gas Strike":           ["Orbital"],
    "Orbital EMS Strike":           ["Orbital"],
    "Orbital Smoke Strike":         ["Orbital"],
    "Orbital Napalm Strike":        ["Orbital"],
    "Airburst Rocket Launcher":     ["Weapon"],
    "Autocannon":                   ["Weapon"],
    "Expendable Anti-Tank":         ["Weapon"],
    "Flamethrower":                 ["Weapon"],
    "Laser Cannon":                 ["Weapon"],
    "Stalwart":                     ["Weapon"],
    "Machine Gun":                  ["Weapon"],
    "Arc Thrower":                  ["Weapon"],
    "Grenade Launcher":             ["Weapon"],
    "Anti-Material Rifle":          ["Weapon"],
    "Railgun":                      ["Weapon"],
    "Recoilless Rifle":             ["Weapon"],
    "Spear":                        ["Weapon"],
    "Sterilizer":                   ["Weapon"],
    "Quasar Cannon":                ["Weapon"],
    "Heavy Machine Gun":            ["Weapon"],
    "MLS-4X Commando":              ["Weapon"],
    "Guard Dog Dog Breath":         ["Backpack"],
    "Guard Dog Rover":              ["Backpack"],
    "Guard Dog":                    ["Backpack"],
    "Jump Pack":                    ["Backpack"],
    "Supply Pack":                  ["Backpack"],
    "Shield Generator Pack":        ["Backpack"],
    "Ballistic Shield Backpack":    ["Backpack"],
    "Tesla Tower":                  ["Sentry"],
    "Mortar Sentry":                ["Sentry"],
    "EMS Mortar Sentry":            ["Sentry"],
    "Machine Gun Sentry":           ["Sentry"],
    "Gatling Sentry":               ["Sentry"],
    "Anti-Personnel Minefield":     ["Sentry"],
    "Anti-Tank Mines":              ["Sentry"],
    "Incendiary Mines":             ["Sentry"],
    "Shield Generator Relay":       ["Sentry"],
    "HMG Emplacement":              ["Sentry"],
    "Autocannon Sentry":            ["Sentry"],
    "Rocket Sentry":                ["Sentry"],
    "Patriot Exosuit":              ["Vehicle"],
    "Emancipator Exosuit":          ["Vehicle"],
}

SAVEGAME = pg.USEREVENT + 1
ENDGAME = pg.USEREVENT + 2

IMAGEBASEPATH = "HD2RoguelikeGen/HD2 Icons/"